### ISSUE TITLE
Redirecionar para o Pagseguro, como fazer ?

### ISSUE THREAD

**Issue by leosmeira** [heavenstudio/spree_pag_seguro#5]
Como faço para redirecionar o comprador para o Pagseguro após ele escolher a forma de pagamento no Spree e clicar em "Salvar e continuar"??

**Comment by angelim** [comment]
Oi @leosmeira,
Eu não estou usando mais esta gem, mas na época eu fiz um tratamento no meu `CheckoutControllerDecorator`

```
...
if @order.state == "complete" && @order.payment_method.class == Spree::PaymentMethod::PagSeguroMethod && !@order.paid?
  redirect_to PagSeguro::Payment.checkout_payment_url(@order.payment.source.code)
...
```

Como alternativa, você também pode não finalizar o pedido com "continue e save" e mostrar um link para o usuário ir para o PagSeguro. 

```
<%= link_to t("check_out_with_pag_seguro"), PagSeguro::Payment.checkout_payment_url(@order.payment.source.code) %>
```

Na volta o controller de notification completa o pedido.

Espero ter ajudado.

Abraços

**Comment by leosmeira** [comment]
Obrigado Angelim pelos seus esclarecimentos!

**Comment by cassioscabral** [comment]
@angelim Estou adaptando essa gem para o spree 2.1 e esse payment do @order não existe mais. O que é esse payment,  source e code que é acessado ali em @order ?

**Comment by angelim** [comment]
O `payment` era um atalho para o último registro de pagamento de uma ordem. `source` era o método de pagamento, que pode ter seus próprios atributos. `code` era um atributo especial criado para o método de pagamento do pagseguro. Esse código é fornecido pela API do serviço do PagSeguro e usado para encaminhar o usuário para url de pagamento.

**Comment by leosmeira** [comment]
Fiz um redirecionamento automático para o pagseguro:

https://github.com/leosmeira/spree_pag_seguro/blob/master/app/controllers/spree/checkout_controller_decorator.rb

Em 2 de dezembro de 2013 05:01, angelim notifications@github.com escreveu:
